[package]
name = "paf"
version = "0.1.0"
authors = ["Darcy Jones <darcy.ab.jones@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"
snafu = "0.6.0"
